### ISSUE TITLE
How do you construct your toolchain for kindle?

### ISSUE THREAD

**Issue by xeonxu** [llakssz/KindleLazy#1]
I'm using Kindle pw1, and get "./kindlelazy: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by ./kindlelazy)" message when I run kindlelazy in CLI.
After then, I  try to build kindlelazy myself. But seems it cannot link with X11 (cause my toolchain did not contain this lib). Could you please tell me how to get it?
Or shoud you build the bin with --static option?

**Comment by llakssz** [comment]
Here you can get the sources for your kindle, it includes the source for the toolchain to build for kindle.
https://www.amazon.com/gp/help/customer/display.html?nodeId=200203720

I copied the X11 libs from my kindle, to my development computer.

Recently I was told that the modules I included with KindleLazy (.ko files) would not work on PW1, that makes sense.
I believe the source for them is also in the archive that Amazon provides...? So you can compile your own I think.

Either way, I don't think the PW1 even supports usb otg - so doing all of this, it still may not be possible.

Let me know how you get on though, good luck!

**Comment by xeonxu** [comment]
Thanks for reply. But saddly, it seems that pw1 does not support otg. I've already rebuilt three kernel module files for my kindle, and insmod without errors. After then, I got /dev/input/mice and /dev/input/mouse0 device files appear. Then, I tried to insert presentation remote reciever via otg adapter and checked the dmesg info. Nothing happened. No auto detect, no enum procedure start.

Can you post your dmesg while enabling kindlelazy with controller attached? I'd like to find out what's going wrong.

**Comment by mylovesaber** [comment]
> Here you can get the sources for your kindle, it includes the source for the toolchain to build for kindle. https://www.amazon.com/gp/help/customer/display.html?nodeId=200203720
> 
> I copied the X11 libs from my kindle, to my development computer.
> 
> Recently I was told that the modules I included with KindleLazy (.ko files) would not work on PW1, that makes sense. I believe the source for them is also in the archive that Amazon provides...? So you can compile your own I think.
> 
> Either way, I don't think the PW1 even supports usb otg - so doing all of this, it still may not be possible.
> 
> Let me know how you get on though, good luck!

The link doesn't exist any more. I download from here:
https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi.tar.xz

Error while compiling:
```bash
Ubuntu-2204-jammy-amd64-base ~/KindleLazy/src $ make -j$(nproc)
/usr/local/arm/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-g++ -DBUILD_KINDLE kindlelazy.cpp jsoncpp.cpp -o kindlelazy -std=c++0x -lXtst -lX11
kindlelazy.cpp:20:10: fatal error: X11/extensions/XTest.h: No such file or directory
 #include <X11/extensions/XTest.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

What I do:
```bash
root@Ubuntu-2204-jammy-amd64-base ~ # apt-file search "X11/extensions/XTest.h"
libxtst-dev: /usr/include/X11/extensions/XTest.h
root@Ubuntu-2204-jammy-amd64-base ~ # apt install libxtst-dev
```
Still the same wrong info. Is there anything I missed?
