### ISSUE TITLE
Please indicate in readme that Jailbreak is required!

### ISSUE THREAD

**Issue by dsjstc** [llakssz/KindleLazy#2]
I got very excited about this and ordered a PW3.

Now I am sad.  A modern PW3 has firmware 5.8.11, and [cannot be jailbroken](https://wiki.mobileread.com/wiki/5_x_Jailbreak) without [splitting the case](http://blog.the-ebook-reader.com/2015/07/23/step-by-step-guide-for-jailbreaking-kindles-using-serial-port-method/) and [soldering leads](https://www.mobileread.com/forums/showthread.php?t=263113) to provide for a 1.8V tty adapter.

**Comment by RayBB** [comment]
Agreed

**Comment by llakssz** [comment]
I would have assumed anyone would at least done a tiny bit of research into this before you purchased a device.
It says in the description that it's a KUAL extension.
I hope you were able to return it ok! 👍
