### ISSUE TITLE
Is it possible to purchase from you?

### ISSUE THREAD

**Issue by chainastole** [llakssz/KindleLazy#4]
Hello,
My Kindle is 7-th generation, Serial Number 90C6 XXXX XXXX XXXX. Will your hack work for it? If yes, is it possible to purchase? If not, is it possible to have instructions for dummies? Will I need to make some more preparations like jailbreaking? I am not a Kindle hacker and is interested because my wife has temporary disabilities after operation on spinal cord and that could work well together with tablet stand which I've already purchased.

**Comment by llakssz** [comment]
Hi, very sorry for the slow reply, I hope you see this message.

I'm not sure where you are (China?) - but yes I can help you set up a kindle for your wife.
No payment necessary, ideally I won't need to touch your device but if needed, you can send it to me if you want.
I don't know if it works with Kindle 7th gen/90C6 because I don't have one, I don't think it will be a problem though. I can try my best to try to make it work!

Keep in mind, things like this are quite possible with a normal android tablet I imagine (and without any 'hacking'). So, unless you really want an e-ink device, maybe that is the easiest option.

Anyway, I will wait to hear back form you.

**Comment by chainastole** [comment]
Hello,I am in Israel.To send you the device is not a good option first because it is in over-day use and second because it is not very ethical towards you. If it is possible to instruct me with buying the HW from you it would be preferable.My wife prefers Kindle on iPad. But just for common knowledge, how can it be done with tablet?

**Comment by llakssz** [comment]
Ok so you have an ipad. I have read good things about Apple's accessibility support.
I have never used it, but it seems very possible, and not too difficult to setup.

It seems iBooks supports remote switches that are used by many people who need to control their devices by simple controls.
This video is from 2014, maybe now to do similar things, it is easier?
https://gettecla.com/blogs/news/15015949-how-to-turn-pages-in-ibooks-using-single-switch-and-ios-switch-control

You could to buy something like this: https://www.gokeytech.com/products/tapio-ios-switch-interface-with-lightning-connector which lets you add switches. It seems the standard connector for these switches is the 3.5mm connector, like headphones.

Here are some links that look interesting on how to set up turning pages via switches:
https://www.airturn.com/support/product-support/how-to/how-to-turn-pages-in-ibooks


There are some other tricks, you can get the ipad to turn the page for you. Technically, you make it read the book out loud, like an audio book - but you turn the sound off. So, the pages seem to turn automatically. I assume you can change the speed.
https://www.themacquad.com/home/2018/4/1/auto-turn-book-pages-in-ios

I see some people saying you can turn a page in iBooks simply with a bluetooth keyboard, and the up+down buttons.

Let me know if you need help.

If it was me, first, I was try a bluetooth keyboard. Second, get some switches.

**Comment by chainastole** [comment]
Thanks a lot for your comprehensive response. Nevertheless, my wife prefers Kindle for books and it seem she is quite accustomed to turn page by hand. Anyway I provided her a Kindle stand which is attached to bed and makes it significantly easier to handle.

**Comment by llakssz** [comment]
I am not interested in making money/profit, but if you truly want a hacked kindle with some instructions, and a usb controller - exactly like this (it's my video): https://www.youtube.com/watch?v=Ti_KD58UWuc
If this is what you want and you are happy to pay for the price of a new kindle paperwhite, usb controller, and tracked+insured shipping to Israel, I am happy to do this for you.

**Comment by chainastole** [comment]
Hi, Joshua.I talked to my wife. She says she is good without this remote paging option. Anyway thanks for your generous proposal.

**Comment by llakssz** [comment]
No problem - happy to help! 👍
(I have edited all your messages to remove your personal details)
